// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoxzLwncpKCd2HYqpAF3IR46ySWH2eqI',
    appId: '1:311059865252:web:511642f06642cec2dbd031',
    messagingSenderId: '311059865252',
    projectId: 'sabari-cars',
    authDomain: 'sabari-cars.firebaseapp.com',
    storageBucket: 'sabari-cars.firebasestorage.app',
    measurementId: 'G-GBV3N055SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXXhcbtJVQDT9qo231ArhxoLM76jR3ch4',
    appId: '1:311059865252:android:4bafafea75029e7cdbd031',
    messagingSenderId: '311059865252',
    projectId: 'sabari-cars',
    storageBucket: 'sabari-cars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOsuTnV-f6oEbm9JYtZBWp99AGDqIodHw',
    appId: '1:311059865252:ios:1029b1345423e29adbd031',
    messagingSenderId: '311059865252',
    projectId: 'sabari-cars',
    storageBucket: 'sabari-cars.firebasestorage.app',
    iosClientId: '311059865252-62h16ll75vopor5ijdstptttstn7nt6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabaricars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOsuTnV-f6oEbm9JYtZBWp99AGDqIodHw',
    appId: '1:311059865252:ios:1029b1345423e29adbd031',
    messagingSenderId: '311059865252',
    projectId: 'sabari-cars',
    storageBucket: 'sabari-cars.firebasestorage.app',
    iosClientId: '311059865252-62h16ll75vopor5ijdstptttstn7nt6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabaricars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVoxzLwncpKCd2HYqpAF3IR46ySWH2eqI',
    appId: '1:311059865252:web:720badf24274f03adbd031',
    messagingSenderId: '311059865252',
    projectId: 'sabari-cars',
    authDomain: 'sabari-cars.firebaseapp.com',
    storageBucket: 'sabari-cars.firebasestorage.app',
    measurementId: 'G-CMYV89EHZX',
  );
}
